tech(recursion/nth-fibonacci): fibonacci
AlgoDataStructure/dsalgo-python-solutions pull request #2
Opened 2021-06-18 06:56 UTC by sriramanvellingiri

#1

2021-06-20 09:35 UTC, shangan23 requested changes
Changes requested

2021-06-20 09:35 UTC, shangan23 commented on recursion-nth-fibonacci.py
> +		sumNo = defaultArray[0] + defaultArray[1]
change `sumNo` variable to `sum`

2021-06-20 09:35 UTC, shangan23 commented on recursion-nth-fibonacci.py
> +	if n == 1:
move this if-block before count init since there is no need for count assignment and further while check. correct me if I am wrong

2021-06-20 14:01 UTC, sriramanvellingiri commented on recursion-nth-fibonacci.py
> +	if n == 1:
DOne

2021-06-20 14:01 UTC, sriramanvellingiri commented on recursion-nth-fibonacci.py
> +		sumNo = defaultArray[0] + defaultArray[1]
Changed

2021-06-22 03:04 UTC, shangan23 requested changes
change required

2021-06-22 03:04 UTC, shangan23 commented on recursion-nth-fibonacci.py
> +	else:
`else` is not required

2021-06-22 15:45 UTC, sriramanvellingiri commented on recursion-nth-fibonacci.py
> +	else:
Resolved

2021-06-22 17:58 UTC, merged